apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devday-demoapp
resources:
  - namespace.yaml
  - storage.yaml
  - backend.yaml
  - frontend.yaml
images:
  - name: devday-frontend
    newName: acrokzfv5l7xea3m.azurecr.io/devday-frontend
    newTag: d6b62b7c0073079c0c5dfd5bd0bbceb0eb408ba1
  - name: devday-backend
    newName: acrokzfv5l7xea3m.azurecr.io/devday-backend
    newTag: d6b62b7c0073079c0c5dfd5bd0bbceb0eb408ba1
